### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by finnteegen** [cau-placc/ghc-language-plugin#4]
The evaluation of the expression `[let {i = 1; _ = putStrLn $ show "Name?"; name = getLine } in name]` results in a crash (segmentation fault).

**Comment by finnteegen** [comment]
The problem seems to be the `$` operator. Using parentheses works fine.

**Comment by finnteegen** [comment]
In fact, `id $ ()` crashes, too. So definitely the `$` operator.

**Comment by Ziharrk** [comment]
($) was never actually lifted. Fixed now
