### ISSUE TITLE
Type check error with `$`

### ISSUE THREAD

**Issue by finnteegen** [cau-placc/ghc-language-plugin#5]
The expression `putStrLn $ "Hallo" ++ " Kai"` does not type check. In contrast, `putStrLn ("Hallo" ++ " Kai")` does. So, presumably this issue is related to #4 as it is again the `$` operator that causes the problem here.

**Comment by Ziharrk** [comment]
($) was missing a fixity declaration.
Thus, your example parsed as `(putStrLn $ "Hallo") ++ " Kai"` which is obviously not type correct.

**Comment by Ziharrk** [comment]
Fixed now
